[package]
name = "Solitaire"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.9.3"
rand = "0.8.5"
oorandom = "11.1.3"
getrandom = "0.2.12"
image = "0.24.9"